version: '3.8'

services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    ports:
      - "3306:3306" # 映射端口 3306 到宿主机的 3306
    environment:
      - MYSQL_ROOT_PASSWORD=casdoor # 设置 MySQL root 用户的密码
      - MYSQL_DATABASE=casdoor # 创建一个名为 casdoor 的数据库
    volumes:
      - ./mysql-data:/var/lib/mysql # 将容器的 /var/lib/mysql 挂载到宿主机的 mysql-data 目录
    restart: always # 容器崩溃后自动重启

  casdoor-1:
    image: casbin/casdoor:v1.814.0
    container_name: casdoor-1
    ports:
      - "8001:8000" # 映射端口 8000 到宿主机的 8001
    volumes:
      - ./shared-tmp:/tmp # 将容器的 /tmp 挂载到宿主机的 shared-tmp 目录
    environment:
      - driverName = mysql
      - dataSourceName=root:casdoor@tcp(mysql:3306)/ # 设置数据源名称
      - CASDOOR_NAME=casdoor-1 # 设置环境变量以区分实例
    restart: always
    depends_on:
      - mysql

  casdoor-2:
    image: casbin/casdoor:v1.814.0
    container_name: casdoor-2
    ports:
      - "8002:8000" # 映射端口 8000 到宿主机的 8002
    volumes:
      - ./shared-tmp:/tmp # 将容器的 /tmp 挂载到宿主机的 shared-tmp 目录
    environment:
      - driverName = mysql
      - dataSourceName=root:casdoor@tcp(mysql:3306)/ # 设置数据源名称
      - CASDOOR_NAME=casdoor-2 # 设置环境变量以区分实例
    restart: always
    depends_on:
      - casdoor-1

  casdoor-3:
    image: casbin/casdoor:v1.814.0
    container_name: casdoor-3
    ports:
      - "8003:8000" # 映射端口 8000 到宿主机的 8003
    volumes:
      - ./shared-tmp:/tmp # 将容器的 /tmp 挂载到宿主机的 shared-tmp 目录
    environment:
      - driverName = mysql
      - dataSourceName=root:casdoor@tcp(mysql:3306)/ # 设置数据源名称
      - CASDOOR_NAME=casdoor-3 # 设置环境变量以区分实例
    restart: always
    depends_on:
      - casdoor-1